### PR TITLE
Add sorting to project in issue form

### LINKED ISSUE #73: Projects not sorted by name
Hi

We migrated to the Atlassian Cloud. Now the drop-down (JIRA project) inside the dialog to open a new issue is not sorted by name. So finding the correct project name is difficult.

Is there a way that the projects are sorted, before added to the drop-down?

Thank you.

### PR DESCRIPTION
**Pull request by premar**
Resolves #73

### CODE REVIEW

**Comment by mrimann** [comment]
I inofficially approve this change after having tested this together with @premar on our environment. It solves the problem of sorting the JIRA projects alphabetically and also considers the strange sorting behaviour of sorting "A-Z" followed by "a-z" instead of the case-insensitive "A-Z" sorting expected by humans.

@theFeu maybe could you have a look at this tiny one-liner improvement and see if it can be merged, that would be awesome!

**Comment by theFeu** [comment]
`SORT_STRING` and `SORT_NATURAL` don't really work together, you could take one of them out and then I would merge it!

**Comment by nilmerg** [comment]
@cla-bot check

**Comment by premar** [comment]
@cla-bot check

**Comment by bobapple** [comment]
@cla-bot check

**Pull request merged**
