### PR TITLE
making JIRA fields configurable

### PR DESCRIPTION
**Pull request by verboEse**
Hi.
our JIRA team doesn't allow us to define "special" variables called "IcingaKey" and "IcingaStatus". Instead we have to "re-use" other fields that are already defined (for other departments).

I changed the code so these fields are now configure options in config.ini, maybe you will find that useful :-)

### CODE REVIEW

**Review by Thomas-Gelf — CHANGES_REQUESTED** [review]
Thanks for this Pull-Request, I like the proposal! Please:

* use lowerCase initial characters for your variable names (e.g. `$keyField` instead of `$KeyField`)
* `[ui]` is IMHO not the right place for these new settings, please introduce a new `[jira_key_fields]` section with `icinga_status = "icingaStatus"` and `icinga_object = "icingaKey"`
* not required, but just to fit the rest of the code: `'text' . $var` instead of `'text'.$var`

**Comment by verboEse** [comment]
Hi Thomas.
Thanks for the review and the great suggestions. I followed them and changed my PR.

**Comment by verboEse** [comment]
I accidentally checked in with a wrong account, so I will have to rework this. I will eventually create a new change request for this.

**Comment by fl0wx** [comment]
@verboEse: Hey do you know when you will open up a new PR for that? :)

**Comment by fl0wx** [comment]
@verboEse  Any news ?

**Comment by fl0wx** [comment]
@verboEse: Hey, will you open this PR again?

**Comment by verboEse** [comment]
I just added #96, which is essentially this PR, with just the commit authors fixed.

**Pull request closed without merging**
